api_platform:
  show_webby: false
  patch_formats:
    json: ['application/merge-patch+json']
  swagger:
    versions: [3]
  formats:
    jsonld:
      mime_types: [ 'application/ld+json' ]
    json:
      mime_types: [ 'application/json' ]

  error_formats:
    jsonproblem:
      mime_types: [ 'application/problem+json' ]
    jsonld:
      mime_types: [ 'application/ld+json' ]

  path_segment_name_generator: App\Core\Infrastructure\Api\PathSegmentNameGeneratorSlash
