doctrine:
  dbal:
    charset:  UTF8
    types:
      datetime_immutable: App\Core\Infrastructure\Share\Doctrine\DateTimeType
      datetime_micro: App\Core\Infrastructure\Share\Doctrine\DateTimeMicrosecondsType
      uuid: Ramsey\Uuid\Doctrine\UuidType
      uuid_binary: Ramsey\Uuid\Doctrine\UuidBinaryType
      uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
    mapping_types:
      uuid_binary: binary
      uuid_binary_ordered_time: binary
  orm:
    auto_generate_proxy_classes: '%kernel.debug%'
    entity_managers:
      default:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
