services:
  App\Core\Domain\Swagger\SwaggerSpecialIdDecorator:
    decorates: 'api_platform.swagger.normalizer.documentation'
    arguments: ['@App\Core\Domain\Swagger\SwaggerSpecialIdDecorator.inner']
    autoconfigure: false
